{{- if .Values.apachePersistenceClaim.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-apache
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.apachePersistenceClaim.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.apachePersistenceClaim.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.apachePersistenceClaim.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.apachePersistenceClaim.size | quote }}
{{- end -}}
